routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;
// use App\Http\Controllers\

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::resource ('produk', ProdukController::class);

// Route::get('/vproduk', function () {
//     return view('produk.vproduk');
// });

// Route::get('/vproduk', function () {
//     return view('produk.index');
// });

Route::resource('produk', ProdukController::class);
Route::get('/vproduk', function () {
    return view('kategori.vkategori');
});

Route::resource ('kategori', KategoriController::class);

Route::get('/vkategori', function () {
    return view('kategori.vkategori');
});

Route::get('/addkategori', function () {
    return view('kategori.addkategori');
});

Route::resource ('customer', CustomerController::class);
Route::get('/vcustomer', function () {
    return view('customer.vcustomer');
});
Route::get('/addcustomer', function () {
    return view('customer.addcustomer');
});

app/Models/Produk.php
<?php

namespace App\Models;
// namespace produk;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;
    protected $table = "produk";
    // protected $primaryKey = "id";
    protected $fillable = ['kode_produk', 'nama_produk', 'img', 'desk', 'harga', 'stok'];
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Models\Produk;


class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $produksa = Produk::all();
        // return view('produk.index', compact('produksa'));
        // return view('produk.index', ['produksa' => $produksa]);

        // $data = Produk::latest()->paginate(5);
        $produk = Produk::all();

        return view('produk.index', compact(
            'produk'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produk.addproduk');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode_produk' => 'required',
            'nama_produk' => 'required',
            'img' => 'required',
            'desk' => 'required',
            'harga' => 'required',
            'stok' => 'required',
        ]);

        Project::create($request->all());

        return redirect()->route('produk.index')
            ->with('success', 'Project created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Produk $produk)
    {
        return view('produk.show',compact('produk'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produk = Produk::findOrFail($id);

        return view('produk.editproduk', compact(
            'produk'
        ));
        // return view('produk.editproduk',compact('produk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_produk' => 'required',
            'nama_produk' => 'required',
            'img' => 'required',
            'desk' => 'required',
            'harga' => 'required',
            'stok' => 'required',
        ]);

        Project::create($request->all());

        return redirect()->route('produk.index')
            ->with('success', 'Produk created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk->delete();

        return redirect()->route('produk.index')
            ->with('success', 'Produk delete successfully.');
    }
}

resources/views/produk/addproduk.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Breeze Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/flag-icon-css/css/flag-icon.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2/select2.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2-bootstrap-theme/select2-bootstrap.min.css" />
    <link rel="stylesheet" href="../../assets/css/style.css" />
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
  </head>
  <body>
    <div class="container-scroller">
      
    @include('templates.sidebar')

      <div class="container-fluid page-body-wrapper">

        @include('templates.header')

        @yield('content')
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title">Tambah Produk</h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Forms</a></li>
                  <li class="breadcrumb-item active" aria-current="page"> Form elements </li>
                </ol>
              </nav>
            </div>
            <div class="row">
            
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Basic form elements</h4>
                    <p class="card-description">Basic form elements</p>
                    <form action="{{ url('produk.store') }}" method="POST" class="forms-sample">
                      @csrf
                        <div class="form-group">
                          <label for="exampleInputName1">Kode Produk</label>
                          <input type="text" class="form-control" name="kode_produk" id="exampleInputKodeProduk" placeholder="Name" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail3">Nama Produk</label>
                          <input type="text" class="form-control" name="nama_produk" id="exampleInputNamaProduk" placeholder="Email" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Img</label>
                          <input type="text" class="form-control" name="img" id="exampleInputImp" placeholder="Password" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Deskripsi</label>
                          <input type="text" class="form-control" name="desk" id="exampleInputDesk" placeholder="Password" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Harga</label>
                          <input type="text" class="form-control" name="harga" id="exampleInputHarga" placeholder="Password" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Stok</label>
                          <input type="text" class="form-control" name="stok" id="exampleInputStok" placeholder="Password" />
                        </div>
                        {{-- <div class="form-group">
                          <label for="exampleSelectGender">Gender</label>
                          <select class="form-control" id="exampleSelectGender">
                            <option>Male</option>
                            <option>Female</option>
                          </select>
                        </div> --}}
                        {{-- <div class="form-group">
                          <label>File upload</label>
                          <input type="file" name="img[]" class="file-upload-default" />
                          <div class="input-group col-xs-12">
                            <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image" />
                            <span class="input-group-append">
                              <button class="file-upload-browse btn btn-primary" type="button"> Upload </button>
                            </span>
                          </div>
                        </div> --}}
                        {{-- <div class="form-group">
                          <label for="exampleTextarea1">Textarea</label>
                          <textarea
                            class="form-control"
                            id="exampleTextarea1"
                            rows="4"
                          ></textarea>
                        </div> --}}
                        <button type="submit" class="btn btn-primary mr-2"> Submit </button>
                        <a href="{{ url('produk') }}" class="btn btn-sm ml-3 btn-light">Cancel</a>
                      </form>
                  </div>
                </div>
              </div>
            
            </div>
          </div>
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="../../assets/vendors/select2/select2.min.js"></script>
    <script src="../../assets/vendors/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <script src="../../assets/js/file-upload.js"></script>
    <script src="../../assets/js/typeahead.js"></script>
    <script src="../../assets/js/select2.js"></script>
  </body>
</html>

resources/views/produk/editproduk.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Breeze Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/flag-icon-css/css/flag-icon.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2/select2.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2-bootstrap-theme/select2-bootstrap.min.css" />
    <link rel="stylesheet" href="../../assets/css/style.css" />
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
  </head>
  <body>
    <div class="container-scroller">
      
    @include('templates.sidebar')

      <div class="container-fluid page-body-wrapper">

        @include('templates.header')

        @yield('content')
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title">Edit Produk</h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Forms</a></li>
                  <li class="breadcrumb-item active" aria-current="page"> Form elements </li>
                </ol>
              </nav>
            </div>
            <div class="row">
            
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Basic form elements</h4>
                    <p class="card-description">Basic form elements</p>
                    <form action="{{ url('produk.store', $produk->id) }}" method="POST" class="forms-sample">
                      @csrf
                        <div class="form-group">
                          <label for="exampleInputName1">Kode Produk</label>
                          <input type="text" class="form-control" value="{{ $produk->kode_produk }}" id="exampleInputKodeProduk" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail3">Nama Produk</label>
                          <input type="text" class="form-control" value="{{ $produk->nama_produk }}" id="exampleInputNamaProduk" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Img</label>
                          <input type="text" class="form-control" value="{{ $produk->img }}" id="exampleInputImp" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Deskripsi</label>
                          <input type="text" class="form-control" value="{{ $produk->desk }}" id="exampleInputDesk" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Harga</label>
                          <input type="text" class="form-control" value="{{ $produk->harga }}" id="exampleInputHarga" />
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword4">Stok</label>
                          <input type="text" class="form-control" value="{{ $produk->stok }}" id="exampleInputStok" />
                        </div>
                        {{-- <div class="form-group">
                          <label for="exampleSelectGender">Gender</label>
                          <select class="form-control" id="exampleSelectGender">
                            <option>Male</option>
                            <option>Female</option>
                          </select>
                        </div> --}}
                        {{-- <div class="form-group">
                          <label>File upload</label>
                          <input type="file" name="img[]" class="file-upload-default" />
                          <div class="input-group col-xs-12">
                            <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image" />
                            <span class="input-group-append">
                              <button class="file-upload-browse btn btn-primary" type="button"> Upload </button>
                            </span>
                          </div>
                        </div> --}}
                        {{-- <div class="form-group">
                          <label for="exampleTextarea1">Textarea</label>
                          <textarea
                            class="form-control"
                            id="exampleTextarea1"
                            rows="4"
                          ></textarea>
                        </div> --}}
                        <button type="submit" class="btn btn-primary mr-2"> Submit </button>
                        <button class="btn btn-light">Cancel</button>
                      </form>
                  </div>
                </div>
              </div>
            
            </div>
          </div>
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="../../assets/vendors/select2/select2.min.js"></script>
    <script src="../../assets/vendors/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <script src="../../assets/js/file-upload.js"></script>
    <script src="../../assets/js/typeahead.js"></script>
    <script src="../../assets/js/select2.js"></script>
  </body>
</html>

resources/views/produk/index.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Breeze Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/flag-icon-css/css/flag-icon.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2/select2.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2-bootstrap-theme/select2-bootstrap.min.css" />
    <link rel="stylesheet" href="../../assets/css/style.css" />
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
  </head>
  <body>
    <div class="container-scroller">
      
    @include('templates.sidebar')

      <div class="container-fluid page-body-wrapper">

        @include('templates.header')

        @section('content')
            
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title">Tambah Produk</h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Forms</a></li>
                  <li class="breadcrumb-item active" aria-current="page"> Form Add </li>
                </ol>
              </nav>
            </div>
            <div class="row">
            
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                      <div class="card-body">
                        <h4 class="card-title">List Produk</h4>
                        <p class="card-description"> Add class <a href="{{ route('produk.create') }}" class="btn btn-sm ml-3 btn-success" role="button">Add</a>
                        </p>
                        <div class="table-responsive">
                          <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>No</th>
                                <th>Kode Produk</th>
                                <th>Nama Produk</th>
                                <th>Gambar</th>
                                <th>Deskripsi</th>
                                <th>Harga</th>
                                <th>Stok</th>
                              </tr>
                            </thead>
                            <tbody>
                                
                                @foreach ($produk as $produks)
                                    <tr>
                                        <td>{{ $produks->kode_produk }}</td>
                                        <td>{{ $produks->nama_produk }}</td>
                                        <td>{{ $produks->gambar }}</td>
                                        <td>{{ $produks->desk }}</td>
                                        <td>{{ $produks->harga }}</td>
                                        <td>{{ $produks->stok }}</td>
                                        <td class="text-center">
                                          <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                              action="{{ route('produk.destroy', $produks->id) }}" method="POST">
                                              <a href="{{ route('produk.edit', $produks->id) }}"
                                                  class="btn btn-sm btn-primary">EDIT</a>
                                              @csrf
                                              @method('DELETE')
                                              <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                          </form>
                                      </td>
                                    </tr>
                                @endforeach
                               
                           
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
            
            </div>
          </div>
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="../../assets/vendors/select2/select2.min.js"></script>
    <script src="../../assets/vendors/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <script src="../../assets/js/file-upload.js"></script>
    <script src="../../assets/js/typeahead.js"></script>
    <script src="../../assets/js/select2.js"></script>
  </body>
</html>

resources/views/produk/vproduk.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Breeze Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/flag-icon-css/css/flag-icon.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2/select2.min.css" />
    <link rel="stylesheet" href="../../assets/vendors/select2-bootstrap-theme/select2-bootstrap.min.css" />
    <link rel="stylesheet" href="../../assets/css/style.css" />
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
  </head>
  <body>
    <div class="container-scroller">
      
    @include('templates.sidebar')

      <div class="container-fluid page-body-wrapper">

        @include('templates.header')

        @yield('content')
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title">Tambah Produk</h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Forms</a></li>
                  <li class="breadcrumb-item active" aria-current="page"> Form elements </li>
                </ol>
              </nav>
            </div>
            <div class="row">
            
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                      <div class="card-body">
                        <h4 class="card-title">List Produk</h4>
                        <p class="card-description"> Add class <a href="{{ url('addproduk') }}" class="btn btn-sm ml-3 btn-success" role="button">Add</a> 
                        </p>
                        <div class="table-responsive">
                          <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>No</th>
                                <th>Kode Produk</th>
                                <th>Nama Produk</th>
                                <th>Gambar</th>
                                <th>Deskripsi</th>
                                <th>Harga</th>
                                <th>Stok</th>
                              </tr>
                            </thead>
                            <tbody>
                                {{-- @if(isset($produks)) --}}
                                    @foreach ($produksa as $item)
                                    <tr>
                                        <td>{{ $item->kode_produk }}</td>
                                        <td>{{ $item->nama_produk }}</td>
                                        <td>{{ $item->gambar }}</td>
                                        <td>{{ $item->desk }}</td>
                                        <td>{{ $item->harga }}</td>
                                        <td>{{ $item->stok }}</td>
                                    </tr>
                                    @endforeach
                                {{-- @endif --}}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
            
            </div>
          </div>
          <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="../../assets/vendors/select2/select2.min.js"></script>
    <script src="../../assets/vendors/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <script src="../../assets/js/file-upload.js"></script>
    <script src="../../assets/js/typeahead.js"></script>
    <script src="../../assets/js/select2.js"></script>
  </body>
</html>